const STORAGE_KEY="jukenWeaknessRecordsV1";
const SUMMARY_KEY="jukenKnowledgeSummaryV1";
function localDateKey(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`}
function loadRecords(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}}
function saveRecords(r){localStorage.setItem(STORAGE_KEY,JSON.stringify(r))}
function loadSummary(){try{return JSON.parse(localStorage.getItem(SUMMARY_KEY)||"null")}catch{return null}}
let records=loadRecords(),knowledgeSummary=loadSummary(),pendingResult=null;
document.getElementById("todayLabel").textContent=new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"long",day:"numeric",weekday:"short"}).format(new Date());
function parseResult(text){const get=k=>text.match(new RegExp("^"+k+"\\s*:\\s*(.+)$","mi"))?.[1].trim()||"";const sm=get("SCORE").match(/(\d+)\s*\/\s*(\d+)/);return{date:get("DATE")||localDateKey(),subject:get("SUBJECT")||"未分類",unit:get("UNIT")||"未分類",cause:get("CAUSE")||"未分類",type:get("TYPE")||"UNKNOWN",level:Math.min(5,Math.max(1,Number(get("LEVEL")||2))),score:sm?Number(sm[1]):0,total:sm?Number(sm[2]):10,historical:false,source:"daily"}}
function isValidResult(r){return r.subject!=="未分類"&&r.unit!=="未分類"&&r.total>0}
function isRecentDate(date,days=30){if(!date)return false;const c=new Date();c.setHours(0,0,0,0);c.setDate(c.getDate()-days);return new Date(date+"T00:00:00")>=c}
function analysisRecords(){return records.filter(r=>r.historical||isRecentDate(r.date,30))}
function weaknessGroups(){const m={};analysisRecords().forEach(r=>{if((r.level||1)<=1)return;const k=`${r.subject}｜${r.unit}`;if(!m[k])m[k]={subject:r.subject,unit:r.unit,count:0,level:0,causes:{},items:[],severity:0,historicalCount:0};m[k].count++;m[k].level=Math.max(m[k].level,r.level||1);m[k].causes[r.cause]=(m[k].causes[r.cause]||0)+1;m[k].items.push(r);if(r.historical)m[k].historicalCount++;const rate=Number.isFinite(r.score)&&r.total?Math.max(0,Math.min(1,r.score/r.total)):.55;const weight=r.historical?.9:1.25;m[k].severity+=weight*((r.level||1)*1.4+(1-rate)*5)});return Object.values(m).sort((a,b)=>b.severity-a.severity)}
function statusFor(g){if(g.level>=5||g.severity>=10)return{icon:"👑",label:"BOSS",cls:"boss"};if(g.level>=3||g.severity>=6)return{icon:"⚠️",label:"CHALLENGE",cls:"challenge"};return{icon:"🎯",label:"WATCH",cls:"watch"}}
function renderWeakness(){const e=document.getElementById("weaknessMap"),g=weaknessGroups().slice(0,8),historical=records.filter(r=>r.historical).length;document.getElementById("mapPeriod").textContent=historical?`過去${historical}件＋直近30日`:"直近30日";if(!g.length){e.innerHTML='<div class="empty-state"><div>🗺️</div><strong>まだMAPは空っぽ</strong><p>ミニテストを登録すると、攻略ポイントがここに現れます。</p></div>';return}const mx=Math.max(...g.map(x=>x.severity),1);e.innerHTML=g.map((x,i)=>{const c=Object.entries(x.causes).sort((a,b)=>b[1]-a[1])[0]?.[0]||"不明",s=statusFor(x),priority=Math.max(14,Math.round(x.severity/mx*100));return `<div class="weakness-row ${s.cls}"><div class="weakness-rank">${String(i+1).padStart(2,"0")}</div><div class="weakness-body"><div class="weakness-top"><div><span class="status-badge">${s.icon} ${s.label}</span><strong>${x.subject}｜${x.unit}</strong></div><span class="level-chip">Lv.${x.level}</span></div><div class="priority-label"><span>攻略優先度</span><b>${priority}%</b></div><div class="bar"><span style="width:${priority}%"></span></div><div class="weakness-meta"><span>📚 記録 ${x.count}件</span><span>🧩 ${c}</span>${x.historicalCount?`<span>🕘 過去${x.historicalCount}件</span>`:""}</div></div></div>`}).join("")}
function renderMissions(){const g=weaknessGroups().slice(0,2),items=[["📷","今日のミニテストを登録"],...(g.length?g.map(x=>[statusFor(x).icon,`${x.subject}「${x.unit}」を攻略`]):[["🧠","最初の弱点データを登録する"]])];document.getElementById("missionList").innerHTML=items.map(i=>`<div class="mission"><div class="mission-badge">${i[0]}</div><strong>${i[1]}</strong></div>`).join("")}
function renderStreak(){const days=[...new Set(records.filter(r=>!r.historical&&r.date).map(r=>r.date))].sort().reverse();let s=0,d=new Date();d.setHours(0,0,0,0);for(let i=0;i<60;i++){const k=localDateKey(d);if(days.includes(k))s++;else if(i>0)break;d.setDate(d.getDate()-1)}document.getElementById("streakCount").textContent=s}
function renderMastered(){const e=document.getElementById("masteredList"),by={};records.filter(r=>!r.historical&&r.date&&r.total>0).forEach(r=>{const k=`${r.subject}｜${r.unit}`;(by[k]??=[]).push(r)});const m=[];for(const[k,a]of Object.entries(by)){const l=a.slice().sort((x,y)=>x.date.localeCompare(y.date)).slice(-3);if(l.length>=3&&l.every(x=>x.score/x.total>=.8))m.push(k)}e.innerHTML=m.length?m.slice(0,5).map(x=>`<div class="mastered">🏆 <strong>${x}</strong> <span class="muted">MASTERED</span></div>`).join(""):'<p class="muted">日々の記録で3回連続80%以上になると攻略済みに表示します。</p>'}
function drawChart(){const c=document.getElementById("scoreChart"),x=c.getContext("2d"),f=document.getElementById("subjectFilter").value,d=records.filter(r=>(f==="ALL"||r.subject===f)&&Number.isFinite(r.score)&&r.total>0).slice().sort((a,b)=>{const ak=a.historical?(a.sequence||0):10000+(a.date?Date.parse(a.date):0),bk=b.historical?(b.sequence||0):10000+(b.date?Date.parse(b.date):0);return ak-bk}).slice(-12),w=c.width,h=c.height,p=42;x.clearRect(0,0,w,h);x.strokeStyle="#d1d5db";x.lineWidth=1;for(let i=0;i<=4;i++){const y=p+(h-2*p)*i/4;x.beginPath();x.moveTo(p,y);x.lineTo(w-p,y);x.stroke()}x.fillStyle="#667085";x.font="22px -apple-system";[100,75,50,25,0].forEach((v,i)=>x.fillText(v+"%",4,p+(h-2*p)*i/4+7));if(!d.length){x.fillText("データなし",p+20,h/2);return}const pts=d.map((r,i)=>({x:p+(w-2*p)*(d.length===1?.5:i/(d.length-1)),y:p+(h-2*p)*(1-r.score/r.total)}));x.strokeStyle="#2563eb";x.lineWidth=5;x.beginPath();pts.forEach((q,i)=>i?x.lineTo(q.x,q.y):x.moveTo(q.x,q.y));x.stroke();x.fillStyle="#0f172a";pts.forEach(q=>{x.beginPath();x.arc(q.x,q.y,6,0,Math.PI*2);x.fill()})}
function summaryPromptLines(){if(!knowledgeSummary)return[];return Object.entries(knowledgeSummary).map(([subject,v])=>`- ${subject}: 強み=${(v.strengths||[]).join("・")} / 優先弱点=${(v.priorityWeaknesses||[]).join("・")} / 所見=${v.observation||""}`)}
function buildPrompt(){const g=weaknessGroups().slice(0,7),lines=g.map(x=>`- ${x.subject}「${x.unit}」：重要度Lv.${x.level}、記録${x.count}件、主な原因=${Object.entries(x.causes).sort((a,b)=>b[1]-a[1])[0]?.[0]||"不明"}`),summary=summaryPromptLines();return `あなたは高校受験指導の専門家です。\n以下は私専用の弱点カルテです。英進館の過去ミニテストと直近の記録を材料にしています。\n\n【過去テストからの基礎傾向】\n${summary.length?summary.join("\n"):"- まだ基礎傾向データはありません。"}\n\n【現在の攻略優先度】\n${lines.join("\n")||"- まだ十分な弱点データがありません。"}\n\nこの履歴を踏まえて、私専用の確認問題を5問作ってください。\n\n条件：\n1. 最優先弱点を2〜3問、次点を1〜2問、定着確認を1問程度にする\n2. 高校受験で必要な形式にする\n3. いきなり答え・解説は表示しない\n4. 私が5問すべて回答してから採点する\n5. 間違えた場合はヒントを1段階ずつ出す\n6. 採点後、各問を教科・単元・原因・理解不足/ケアレスミスに分類する\n7. 最後に #RESULT / DATE / SUBJECT / UNIT / CAUSE / TYPE / LEVEL / SCORE の形式で出力する`}
function refresh(){renderWeakness();renderMissions();renderStreak();renderMastered();drawChart();updateKnowledgeStatus()}
function showToast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function showPreview(r){pendingResult=r;document.getElementById("pvSubject").textContent=r.subject;document.getElementById("pvScore").textContent=`${r.score}/${r.total}`;document.getElementById("pvUnit").textContent=r.unit;document.getElementById("pvLevel").textContent=`Lv.${r.level}`;document.getElementById("pvCause").textContent=r.cause;document.getElementById("resultPreview").classList.remove("hidden")}
function updateKnowledgeStatus(){const n=records.filter(r=>r.historical).length,e=document.getElementById("knowledgeStatus");if(e)e.textContent=n?`過去データ：${n}件 登録済み`:"過去データ：未登録"}
async function importKnowledgeFile(file){try{const text=await file.text(),data=JSON.parse(text);if(!data||!Array.isArray(data.records))throw new Error("invalid");const existingIds=new Set(records.map(r=>r.id).filter(Boolean));let added=0;for(const raw of data.records){const r={...raw,historical:true,source:"past-import",date:null};if(r.id&&existingIds.has(r.id))continue;records.push(r);if(r.id)existingIds.add(r.id);added++}saveRecords(records);if(data.summary){knowledgeSummary=data.summary;localStorage.setItem(SUMMARY_KEY,JSON.stringify(data.summary))}refresh();showToast(added?`📦 過去データ${added}件を取り込みました`:`📦 すでに取り込み済みです`)}catch(err){showToast("JSONを読み込めませんでした")}}
refresh();
const reg=document.getElementById("registerDialog");document.getElementById("openRegister").onclick=()=>{pendingResult=null;document.getElementById("resultPreview").classList.add("hidden");reg.showModal()};document.getElementById("closeRegister").onclick=()=>reg.close();
document.getElementById("pasteClipboard").onclick=async()=>{try{const text=await navigator.clipboard.readText();document.getElementById("resultInput").value=text;const r=parseResult(text);if(!isValidResult(r))throw new Error();showPreview(r)}catch{showToast("#RESULTをコピーしてから、もう一度押してね")}};
document.getElementById("previewManual").onclick=()=>{const text=document.getElementById("resultInput").value.trim();if(!text)return showToast("#RESULTを貼り付けてね");const r=parseResult(text);if(!isValidResult(r))return showToast("教科・単元・SCOREを確認してね");showPreview(r)};
document.getElementById("saveResult").onclick=()=>{if(!pendingResult)return showToast("先に読み取りをしてね");records.push(pendingResult);saveRecords(records);pendingResult=null;document.getElementById("resultInput").value="";reg.close();refresh();showToast("🎉 データGET！ 弱点MAPを更新しました")};
const pd=document.getElementById("problemDialog");document.getElementById("generateProblems").onclick=()=>{document.getElementById("problemPrompt").value=buildPrompt();pd.showModal()};document.getElementById("closeProblemDialog").onclick=()=>pd.close();document.getElementById("copyPrompt").onclick=async()=>{try{await navigator.clipboard.writeText(document.getElementById("problemPrompt").value);showToast("📋 今日の5問プロンプトをコピーしました")}catch{document.getElementById("problemPrompt").select()}};document.getElementById("subjectFilter").onchange=drawChart;
const hd=document.getElementById("helpDialog");document.getElementById("openHelp").onclick=()=>hd.showModal();document.getElementById("closeHelp").onclick=()=>hd.close();document.getElementById("startApp").onclick=()=>{localStorage.setItem("jukenOnboarded","1");hd.close()};async function copyAnalysisPrompt(button){const text="今日のミニテストを分析して";try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent="✓ コピーしました";setTimeout(()=>button.textContent=old,1400)}catch{alert(text)}}document.querySelectorAll(".copy-analysis").forEach(b=>b.addEventListener("click",()=>copyAnalysisPrompt(b)));
const importBtn=document.getElementById("importKnowledgeBtn"),knowledgeFile=document.getElementById("knowledgeFile");if(importBtn&&knowledgeFile){importBtn.onclick=()=>knowledgeFile.click();knowledgeFile.onchange=()=>{const f=knowledgeFile.files?.[0];if(f)importKnowledgeFile(f);knowledgeFile.value=""}}
if(!localStorage.getItem("jukenOnboarded"))setTimeout(()=>hd.showModal(),250);if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");